spring:
  application:
    name: HEAR

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  flyway:
    baseline-on-migrate: true

  jwt:
    accessTokenExpiration: 86400
    refreshTokenExpiration: 2592000

  profiles:
    active: prod

server:
  port: 8080
