DELIMITER $$

CREATE TRIGGER Student_User_unique
    BEFORE INSERT ON STUDENT
    FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM FACULTY_MEMBER WHERE User_id = NEW.User_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'This user is already a faculty member.';
END IF;
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER Student_User_unique_upd
    BEFORE UPDATE ON STUDENT
    FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM FACULTY_MEMBER WHERE User_id = NEW.User_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'This user is already a faculty member.';
END IF;
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER Faculty_User_unique
    BEFORE INSERT ON FACULTY_MEMBER
    FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM STUDENT WHERE User_id = NEW.User_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'This user is already a student.';
END IF;
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER Faculty_User_unique_upd
    BEFORE UPDATE ON FACULTY_MEMBER
    FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM STUDENT WHERE User_id = NEW.User_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'This user is already a student.';
END IF;
END$$

DELIMITER ;